export const DELHI_METRO_STATIONS: string[] = [
  "Adarsh Nagar",
  "AIIMS",
  "Akshardham",
  "Anand Vihar",
  "Arjan Garh",
  "Ashok Park Main",
  "Azadpur",
  "Badarpur",
  "Barakhamba Road",
  "Botanical Garden",
  "Central Secretariat",
  "Chandni Chowk",
  "Chawri Bazar",
  "Chhattarpur",
  "Civil Lines",
  "Dilshad Garden",
  "Dwarka",
  "Dwarka Mor",
  "Dwarka Sector 8",
  "Dwarka Sector 9",
  "Dwarka Sector 10",
  "Dwarka Sector 11",
  "Dwarka Sector 12",
  "Dwarka Sector 13",
  "Dwarka Sector 14",
  "Dwarka Sector 21",
  "Ghitorni",
  "Golf Course",
  "Govindpuri",
  "Green Park",
  "Guru Dronacharya",
  "Hauz Khas",
  "Huda City Centre",
  "IFFCO Chowk",
  "INA",
  "Inderlok",
  "Indraprastha",
  "Jahangirpuri",
  "Janakpuri East",
  "Janakpuri West",
  "Jangpura",
  "Janpath",
  "Jasola",
  "Jhandewalan",
  "Jhilmil",
  "JLN Stadium",
  "Jor Bagh",
  "Kailash Colony",
  "Kalkaji Mandir",
  "Kanhaiya Nagar",
  "Karkarduma",
  "Karol Bagh",
  "Kashmere Gate",
  "Kaushambi",
  "Keshav Puram",
  "Khan Market",
  "Kirti Nagar",
  "Kohat Enclave",
  "Lajpat Nagar",
  "Laxmi Nagar",
  "Madipur",
  "Malviya Nagar",
  "Mandi House",
  "Mansarovar Park",
  "Mayur Vihar Extension",
  "Mayur Vihar-I",
  "MG Road",
  "Model Town",
  "Mohan Estate",
  "Moolchand",
  "Moti Nagar",
  "Mundka",
  "Nangloi",
  "Nangloi Railway Station",
  "Nawada",
  "Nehru Place",
  "Netaji Subhas Place",
  "New Ashok Nagar",
  "New Delhi",
  "Nirman Vihar",
  "Noida City Centre",
  "Noida Sector 15",
  "Noida Sector 16",
  "Noida Sector 18",
  "Okhla",
  "Paschim Vihar East",
  "Paschim Vihar West",
  "Patel Chowk",
  "Patel Nagar",
  "Peeragarhi",
  "Pitam Pura",
  "Pragati Maidan",
  "Pratap Nagar",
  "Preet Vihar",
  "Pul Bangash",
  "Punjabi Bagh",
  "Qutab Minar",
  "Race Course",
  "Rajdhani Park",
  "Rajendra Place",
  "Rajiv Chowk",
  "Rajouri Garden",
  "Ramesh Nagar",
  "Rithala",
  "Rohini East",
  "Rohini West",
  "R K Ashram Marg",
  "Saket",
  "Sarita Vihar",
  "Seelampur",
  "Shadipur",
  "Shahdara",
  "Shastri Nagar",
  "Shastri Park",
  "Shivaji Park",
  "Sikandarpur",
  "Subhash Nagar",
  "Sultanpur",
  "Surajmal Stadium",
  "Tagore Garden",
  "Tilak Nagar",
  "Tis Hazari",
  "Tughlakabad",
  "Udyog Bhawan",
  "Udyog Nagar",
  "Uttam Nagar East",
  "Uttam Nagar West",
  "Vaishali",
  "Vidhan Sabha",
  "Vishwavidyalaya",
  "Welcome",
  "Yamuna Bank"
];
