export const STATION_COORDINATES: { [key: string]: { x: number; y: number } } = {
  // Yellow Line
  "Jahangirpuri": { "x": 480, "y": 50 },
  "Adarsh Nagar": { "x": 480, "y": 80 },
  "Azadpur": { "x": 480, "y": 110 },
  "Model Town": { "x": 480, "y": 140 },
  "Vishwavidyalaya": { "x": 490, "y": 200 },
  "Vidhan Sabha": { "x": 510, "y": 240 },
  "Civil Lines": { "x": 520, "y": 270 },
  "Kashmere Gate": { "x": 530, "y": 300 },
  "Chandni Chowk": { "x": 500, "y": 360 },
  "Chawri Bazar": { "x": 500, "y": 390 },
  "New Delhi": { "x": 500, "y": 420 },
  "Rajiv Chowk": { "x": 500, "y": 450 },
  "Patel Chowk": { "x": 500, "y": 480 },
  "Central Secretariat": { "x": 500, "y": 510 },
  "Udyog Bhawan": { "x": 500, "y": 540 },
  "Race Course": { "x": 500, "y": 570 }, // Note: Lok Kalyan Marg is the new name
  "Jor Bagh": { "x": 500, "y": 600 },
  "INA": { "x": 500, "y": 630 },
  "AIIMS": { "x": 500, "y": 660 },
  "Green Park": { "x": 500, "y": 690 },
  "Hauz Khas": { "x": 500, "y": 720 },
  "Malviya Nagar": { "x": 500, "y": 750 },
  "Saket": { "x": 500, "y": 780 },
  "Qutab Minar": { "x": 500, "y": 810 },
  "Chhattarpur": { "x": 500, "y": 840 },
  "Sultanpur": { "x": 500, "y": 870 },
  "Ghitorni": { "x": 500, "y": 900 },
  "Arjan Garh": { "x": 500, "y": 930 },
  "Guru Dronacharya": { "x": 490, "y": 960 },
  "Sikandarpur": { "x": 470, "y": 990 },
  "MG Road": { "x": 450, "y": 1020 },
  "IFFCO Chowk": { "x": 430, "y": 1050 },
  "Huda City Centre": { "x": 410, "y": 1080 },

  // Red Line
  "Rithala": { "x": 180, "y": 100 },
  "Rohini West": { "x": 210, "y": 115 },
  "Rohini East": { "x": 240, "y": 130 },
  "Pitam Pura": { "x": 270, "y": 145 },
  "Kohat Enclave": { "x": 300, "y": 160 },
  "Netaji Subhas Place": { "x": 330, "y": 175 },
  "Keshav Puram": { "x": 360, "y": 210 },
  "Kanhaiya Nagar": { "x": 380, "y": 240 },
  "Inderlok": { "x": 400, "y": 270 },
  "Shastri Nagar": { "x": 440, "y": 285 },
  "Pratap Nagar": { "x": 470, "y": 295 },
  "Pul Bangash": { "x": 500, "y": 300 },
  "Tis Hazari": { "x": 515, "y": 300 },
  "Shastri Park": { "x": 630, "y": 290 },
  "Seelampur": { "x": 680, "y": 270 },
  "Welcome": { "x": 730, "y": 250 },
  "Shahdara": { "x": 780, "y": 230 },
  "Mansarovar Park": { "x": 830, "y": 210 },
  "Jhilmil": { "x": 880, "y": 190 },
  "Dilshad Garden": { "x": 930, "y": 170 },

  // Blue Line
  "Dwarka Sector 21": { "x": 50, "y": 500 },
  "Dwarka Sector 8": { "x": 50, "y": 450 },
  "IGI Airport": { "x": 200, "y": 600 },
  "Delhi Aerocity": { "x": 280, "y": 570 },
  "Dhaula Kuan": { "x": 360, "y": 540 },
  "Dwarka Sector 9": { "x": 50, "y": 420 },
  "Dwarka Sector 10": { "x": 70, "y": 430 },
  "Dwarka Sector 11": { "x": 90, "y": 440 },
  "Dwarka Sector 12": { "x": 110, "y": 450 },
  "Dwarka Sector 13": { "x": 130, "y": 460 },
  "Dwarka Sector 14": { "x": 150, "y": 470 },
  "Dwarka": { "x": 170, "y": 480 },
  "Dwarka Mor": { "x": 200, "y": 480 },
  "Nawada": { "x": 230, "y": 480 },
  "Uttam Nagar West": { "x": 260, "y": 480 },
  "Uttam Nagar East": { "x": 290, "y": 480 },
  "Janakpuri West": { "x": 320, "y": 480 },
  "Janakpuri East": { "x": 350, "y": 480 },
  "Tilak Nagar": { "x": 380, "y": 480 },
  "Subhash Nagar": { "x": 410, "y": 480 },
  "Tagore Garden": { "x": 400, "y": 460 },
  "Rajouri Garden": { "x": 390, "y": 440 },
  "Ramesh Nagar": { "x": 400, "y": 420 },
  "Moti Nagar": { "x": 410, "y": 400 },
  "Kirti Nagar": { "x": 420, "y": 380 },
  "Shadipur": { "x": 430, "y": 410 },
  "Patel Nagar": { "x": 440, "y": 430 },
  "Rajendra Place": { "x": 450, "y": 450 },
  "Karol Bagh": { "x": 470, "y": 450 },
  "Jhandewalan": { "x": 485, "y": 450 },
  "R K Ashram Marg": { "x": 520, "y": 430 },
  "Barakhamba Road": { "x": 540, "y": 450 },
  "Mandi House": { "x": 580, "y": 450 },
  "Pragati Maidan": { "x": 620, "y": 450 },
  "Indraprastha": { "x": 660, "y": 450 },
  "Yamuna Bank": { "x": 750, "y": 450 },
  "Akshardham": { "x": 800, "y": 480 },
  "Mayur Vihar-I": { "x": 830, "y": 510 },
  "Mayur Vihar Extension": { "x": 860, "y": 540 },
  "New Ashok Nagar": { "x": 890, "y": 570 },
  "Noida Sector 15": { "x": 920, "y": 600 },
  "Noida Sector 16": { "x": 950, "y": 600 },
  "Noida Sector 18": { "x": 980, "y": 600 },
  "Botanical Garden": { "x": 1010, "y": 600 },
  "Golf Course": { "x": 1040, "y": 600 },
  "Noida City Centre": { "x": 1070, "y": 600 },
  "Laxmi Nagar": { "x": 800, "y": 420 },
  "Nirman Vihar": { "x": 840, "y": 410 },
  "Preet Vihar": { "x": 880, "y": 400 },
  "Karkarduma": { "x": 920, "y": 390 },
  "Anand Vihar": { "x": 960, "y": 380 },
  "Vaishali": { "x": 1000, "y": 380 },
  "Kaushambi": { "x": 980, "y": 350 },

  // Green Line
  "Mundka": { "x": 40, "y": 180 },
  "Rajdhani Park": { "x": 70, "y": 190 },
  "Nangloi Railway Station": { "x": 100, "y": 200 },
  "Nangloi": { "x": 130, "y": 210 },
  "Surajmal Stadium": { "x": 160, "y": 220 },
  "Udyog Nagar": { "x": 190, "y": 230 },
  "Peeragarhi": { "x": 230, "y": 250 },
  "Paschim Vihar West": { "x": 260, "y": 260 },
  "Paschim Vihar East": { "x": 290, "y": 270 },
  "Madipur": { "x": 320, "y": 280 },
  "Shivaji Park": { "x": 350, "y": 290 },
  "Punjabi Bagh": { "x": 380, "y": 300 },
  "Ashok Park Main": { "x": 400, "y": 320 },

  // Violet Line
  "Badarpur": { "x": 780, "y": 900 },
  "Tughlakabad": { "x": 760, "y": 870 },
  "Mohan Estate": { "x": 740, "y": 840 },
  "Sarita Vihar": { "x": 720, "y": 810 },
  "Jasola": { "x": 700, "y": 780 },
  "Okhla": { "x": 680, "y": 750 },
  "Govindpuri": { "x": 660, "y": 720 },
  "Kalkaji Mandir": { "x": 640, "y": 690 },
  "Nehru Place": { "x": 620, "y": 660 },
  "Kailash Colony": { "x": 600, "y": 630 },
  "Moolchand": { "x": 580, "y": 600 },
  "Lajpat Nagar": { "x": 560, "y": 570 },
  "Jangpura": { "x": 580, "y": 540 },
  "JLN Stadium": { "x": 580, "y": 510 },
  "Khan Market": { "x": 580, "y": 480 },
  "Janpath": { "x": 540, "y": 480 },

  // Orange Line (Airport Express)
  "Shivaji Stadium": { "x": 450, "y": 510 }
};

export const METRO_LINES = [
  {
    name: "Line-1 (Red)",
    color: "#d12b2f",
    path: ["Rithala", "Rohini West", "Rohini East", "Pitam Pura", "Kohat Enclave", "Netaji Subhas Place", "Keshav Puram", "Kanhaiya Nagar", "Inderlok", "Shastri Nagar", "Pratap Nagar", "Pul Bangash", "Tis Hazari", "Kashmere Gate", "Shastri Park", "Seelampur", "Welcome", "Shahdara", "Mansarovar Park", "Jhilmil", "Dilshad Garden"],
  },
  {
    name: "Line-2 (Yellow)",
    color: "#fddd00",
    path: ["Jahangirpuri", "Adarsh Nagar", "Azadpur", "Model Town", "Vishwavidyalaya", "Vidhan Sabha", "Civil Lines", "Kashmere Gate", "Chandni Chowk", "Chawri Bazar", "New Delhi", "Rajiv Chowk", "Patel Chowk", "Central Secretariat", "Udyog Bhawan", "Race Course", "Jor Bagh", "INA", "AIIMS", "Green Park", "Hauz Khas", "Malviya Nagar", "Saket", "Qutab Minar", "Chhattarpur", "Sultanpur", "Ghitorni", "Arjan Garh", "Guru Dronacharya", "Sikandarpur", "MG Road", "IFFCO Chowk", "Huda City Centre"],
  },
  {
    name: "Line-3 (Blue)",
    color: "#0055a4",
    path: ["Dwarka Sector 21", "Dwarka Sector 8", "Dwarka Sector 9", "Dwarka Sector 10", "Dwarka Sector 11", "Dwarka Sector 12", "Dwarka Sector 13", "Dwarka Sector 14", "Dwarka", "Dwarka Mor", "Nawada", "Uttam Nagar West", "Uttam Nagar East", "Janakpuri West", "Janakpuri East", "Tilak Nagar", "Subhash Nagar", "Tagore Garden", "Rajouri Garden", "Ramesh Nagar", "Moti Nagar", "Kirti Nagar", "Shadipur", "Patel Nagar", "Rajendra Place", "Karol Bagh", "Jhandewalan", "R K Ashram Marg", "Rajiv Chowk", "Barakhamba Road", "Mandi House", "Pragati Maidan", "Indraprastha", "Yamuna Bank", "Akshardham", "Mayur Vihar-I", "Mayur Vihar Extension", "New Ashok Nagar", "Noida Sector 15", "Noida Sector 16", "Noida Sector 18", "Botanical Garden", "Golf Course", "Noida City Centre"],
    subPaths: [
      ["Dwarka Sector 21", "Dwarka Sector 8", "Dwarka Sector 9", "Dwarka Sector 10", "Dwarka Sector 11", "Dwarka Sector 12", "Dwarka Sector 13", "Dwarka Sector 14", "Dwarka", "Dwarka Mor", "Nawada", "Uttam Nagar West", "Uttam Nagar East", "Janakpuri West", "Janakpuri East", "Tilak Nagar", "Subhash Nagar"],
      ["Subhash Nagar", "Tagore Garden", "Rajouri Garden", "Ramesh Nagar", "Moti Nagar", "Kirti Nagar"],
      ["Kirti Nagar", "Shadipur", "Patel Nagar", "Rajendra Place", "Karol Bagh", "Jhandewalan", "R K Ashram Marg", "Rajiv Chowk"],
      ["Rajiv Chowk", "Barakhamba Road", "Mandi House", "Pragati Maidan", "Indraprastha", "Yamuna Bank"],
      ["Yamuna Bank", "Akshardham", "Mayur Vihar-I", "Mayur Vihar Extension", "New Ashok Nagar", "Noida Sector 15", "Noida Sector 16", "Noida Sector 18", "Botanical Garden", "Golf Course", "Noida City Centre"],
    ]
  },
  {
    name: "Line-4 (Blue Branch)",
    color: "#0055a4",
    path: ["Yamuna Bank", "Laxmi Nagar", "Nirman Vihar", "Preet Vihar", "Karkarduma", "Anand Vihar", "Kaushambi", "Vaishali"],
  },
  {
    name: "Line-5 (Green)",
    color: "#53a447",
    path: ["Inderlok", "Ashok Park Main", "Punjabi Bagh", "Shivaji Park", "Madipur", "Paschim Vihar East", "Paschim Vihar West", "Peeragarhi", "Udyog Nagar", "Surajmal Stadium", "Nangloi", "Nangloi Railway Station", "Rajdhani Park", "Mundka"],
    subPaths: [
        ["Inderlok", "Ashok Park Main", "Punjabi Bagh", "Shivaji Park", "Madipur", "Paschim Vihar East", "Paschim Vihar West", "Peeragarhi", "Udyog Nagar", "Surajmal Stadium", "Nangloi", "Nangloi Railway Station", "Rajdhani Park", "Mundka"],
        ["Ashok Park Main", "Kirti Nagar"]
    ]
  },
  {
    name: "Line-6 (Violet)",
    color: "#8c1d7e",
    path: ["Mandi House", "Janpath", "Central Secretariat", "Khan Market", "JLN Stadium", "Jangpura", "Lajpat Nagar", "Moolchand", "Kailash Colony", "Nehru Place", "Kalkaji Mandir", "Govindpuri", "Okhla", "Jasola", "Sarita Vihar", "Mohan Estate", "Tughlakabad", "Badarpur"],
  },
  {
    name: "Airport Express (Orange)",
    color: "#f58220",
    path: ["Dwarka Sector 21", "IGI Airport", "Delhi Aerocity", "Dhaula Kuan", "Shivaji Stadium", "New Delhi"],
  },
];
