export const POINTS_OF_INTEREST: { [key: string]: string[] } = {
  'Rajiv Chowk': ['Connaught Place', 'Janpath Market', 'Palika Bazaar'],
  'Chandni Chowk': ['Red Fort', 'Jama Masjid', 'Gurudwara Sis Ganj Sahib'],
  'Kashmere Gate': ['ISBT Kashmere Gate', 'St. James\' Church'],
  'Central Secretariat': ['India Gate', 'Rashtrapati Bhavan', 'Parliament House'],
  'Patel Chowk': ['Jantar Mantar', 'Gurudwara Bangla Sahib'],
  'Khan Market': ['Khan Market Shopping Complex', 'Lodhi Garden'],
  'INA': ['Dilli Haat', 'Sarojini Nagar Market'],
  'Hauz Khas': ['Hauz Khas Village', 'Deer Park'],
  'Qutab Minar': ['Qutub Minar Complex', 'Mehrauli Archaeological Park'],
  'Akshardham': ['Swaminarayan Akshardham Temple'],
  'New Delhi': ['New Delhi Railway Station', 'Paharganj Main Bazaar'],
  'AIIMS': ['All India Institute of Medical Sciences'],
  'Nehru Place': ['Nehru Place Market (IT Hub)'],
  'Kalkaji Mandir': ['Kalkaji Temple', 'Lotus Temple'],
  'Lajpat Nagar': ['Lajpat Nagar Central Market'],
  'Mandi House': ['National School of Drama', 'Triveni Kala Sangam'],
  'Vishwavidyalaya': ['Delhi University (North Campus)'],
};
